import { useState, useEffect } from 'react';
import api from '../../services/api';
import toast from 'react-hot-toast';
import { Lightbulb, Clock, ExternalLink, Star, RefreshCw } from 'lucide-react';

const CATEGORY_COLORS = {
  academics: 'bg-blue-50 text-blue-700 border-blue-100',
  career:    'bg-purple-50 text-purple-700 border-purple-100',
  wellness:  'bg-green-50 text-green-700 border-green-100',
  skill:     'bg-orange-50 text-orange-700 border-orange-100',
  goal:      'bg-pink-50 text-pink-700 border-pink-100',
};

export default function SuggestionsPage() {
  const [suggestionGroups, setSuggestionGroups] = useState([]);
  const [loading, setLoading] = useState(true);
  const [rating, setRating] = useState({});

  const fetchSuggestions = async () => {
    setLoading(true);
    try {
      const { data } = await api.get('/suggestions/today');
      setSuggestionGroups(data.data.suggestions || []);
    } catch (err) {
      toast.error('Failed to load suggestions');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchSuggestions(); }, []);

  const submitFeedback = async (suggestionId, r) => {
    try {
      await api.post('/suggestions/feedback', { suggestionId, rating: r });
      setRating((prev) => ({ ...prev, [suggestionId]: r }));
      toast.success('Thanks for your feedback!');
    } catch {
      toast.error('Failed to save feedback');
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Lightbulb className="w-6 h-6 text-amber-500" />
          <h1 className="text-2xl font-bold text-gray-900">Free Period Suggestions</h1>
        </div>
        <button onClick={fetchSuggestions} disabled={loading} className="btn-secondary flex items-center gap-2 text-sm">
          <RefreshCw className={`w-4 h-4 ${loading ? 'animate-spin' : ''}`} />
          Refresh
        </button>
      </div>

      <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 text-sm text-amber-700">
        These suggestions are personalized based on your interests, career goals, and areas to improve.
        Generated by AI during your free periods.
      </div>

      {loading ? (
        <div className="space-y-4">
          {[1,2].map((i) => (
            <div key={i} className="card space-y-3">
              <div className="h-4 bg-gray-100 rounded animate-pulse w-32" />
              {[1,2,3].map((j) => <div key={j} className="h-20 bg-gray-100 rounded-xl animate-pulse" />)}
            </div>
          ))}
        </div>
      ) : suggestionGroups.length === 0 ? (
        <div className="card text-center py-12">
          <Lightbulb className="w-12 h-12 text-gray-300 mx-auto mb-3" />
          <p className="text-gray-500">No free periods today, or suggestions not yet generated.</p>
        </div>
      ) : (
        suggestionGroups.map((group) => (
          <div key={group._id} className="card space-y-4">
            <h2 className="font-semibold text-gray-800">
              Free Period {group.periodNumber} suggestions
            </h2>

            {group.suggestions.map((item, idx) => (
              <div key={idx} className={`border rounded-xl p-4 ${CATEGORY_COLORS[item.category] || 'bg-gray-50 border-gray-100'}`}>
                <div className="flex items-start justify-between gap-3">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-1">
                      <span className="text-xs font-medium uppercase tracking-wide opacity-70 capitalize">{item.category}</span>
                      <span className="text-xs flex items-center gap-1 opacity-60">
                        <Clock className="w-3 h-3" /> {item.estimatedMinutes} min
                      </span>
                    </div>
                    <p className="font-semibold text-sm">{item.title}</p>
                    <p className="text-xs mt-1 opacity-80 leading-relaxed">{item.description}</p>
                    {item.resourceLinks?.length > 0 && (
                      <div className="flex gap-2 mt-2 flex-wrap">
                        {item.resourceLinks.map((link, li) => (
                          <a key={li} href={link} target="_blank" rel="noopener noreferrer"
                            className="flex items-center gap-1 text-xs underline opacity-70 hover:opacity-100">
                            Resource {li + 1} <ExternalLink className="w-2.5 h-2.5" />
                          </a>
                        ))}
                      </div>
                    )}
                  </div>
                  <div className="text-lg font-bold opacity-30">P{item.priority}</div>
                </div>
              </div>
            ))}

            {/* Rating */}
            <div className="flex items-center gap-2 pt-2">
              <span className="text-xs text-gray-500">Rate these suggestions:</span>
              {[1,2,3,4,5].map((r) => (
                <button
                  key={r}
                  onClick={() => submitFeedback(group._id, r)}
                  className={`text-lg transition-transform hover:scale-110 ${(rating[group._id] || 0) >= r ? 'text-amber-400' : 'text-gray-200'}`}
                >
                  <Star className="w-5 h-5 fill-current" />
                </button>
              ))}
            </div>
          </div>
        ))
      )}
    </div>
  );
}
